version: '3.8'

services:
    scrap-service:
        container_name: scrap-service
        restart: always
        env_file:
            - .env
        environment:
            - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
            - COUNTRY=${COUNTRY}
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/app/data
            - ./logs:/app/logs